spring:
  datasource:
    url: jdbc:h2:mem:test_mem
  #    username: name
  #    password: password
  #    driverClassName: org.h2.Driver
  flyway:
    locations: classpath:db/migration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher